### ISSUE TITLE
Fairseq build fails on build from https://github.com/nicola-decao/fairseq.git@fixing_prefix_allowed_tokens_fn

### ISSUE THREAD

**Issue by DGaffney** [facebookresearch/GENRE#31]
Currently reliably unable to install `fairseq` as specified - likely doing something wrong here, but here's the trace:

```
machine@host:/usr/blah/genre$ conda activate
(base) machine@host:/usr/blah/genre$ pip install git+https://github.com/nicola-decao/fairseq.git@fixing_prefix_allowed_tokens_fn
Collecting git+https://github.com/nicola-decao/fairseq.git@fixing_prefix_allowed_tokens_fn
  Cloning https://github.com/nicola-decao/fairseq.git (to revision fixing_prefix_allowed_tokens_fn) to /tmp/pip-req-build-y8u09mgl
  Running command git clone -q https://github.com/nicola-decao/fairseq.git /tmp/pip-req-build-y8u09mgl
  Running command git checkout -b fixing_prefix_allowed_tokens_fn --track origin/fixing_prefix_allowed_tokens_fn
  Switched to a new branch 'fixing_prefix_allowed_tokens_fn'
  Branch 'fixing_prefix_allowed_tokens_fn' set up to track remote branch 'fixing_prefix_allowed_tokens_fn' from 'origin'.
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied (use --upgrade to upgrade): fairseq==1.0.0a0+4c4d5a7 from git+https://github.com/nicola-decao/fairseq.git@fixing_prefix_allowed_tokens_fn in /home/cryptochat/anaconda3/lib/python3.8/site-packages
Requirement already satisfied: hydra-core<1.1 in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (1.0.6)
Requirement already satisfied: sacrebleu>=1.4.12 in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (1.5.1)
Requirement already satisfied: tqdm in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (4.47.0)
Requirement already satisfied: numpy; python_version >= "3.7" in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (1.18.5)
Requirement already satisfied: cython in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (0.29.21)
Requirement already satisfied: omegaconf<2.1 in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (2.0.6)
Requirement already satisfied: regex in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (2020.6.8)
Requirement already satisfied: torch in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (1.8.1)
Requirement already satisfied: cffi in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from fairseq==1.0.0a0+4c4d5a7) (1.14.0)
Requirement already satisfied: importlib-resources; python_version < "3.9" in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from hydra-core<1.1->fairseq==1.0.0a0+4c4d5a7) (5.1.4)
Requirement already satisfied: antlr4-python3-runtime==4.8 in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from hydra-core<1.1->fairseq==1.0.0a0+4c4d5a7) (4.8)
Requirement already satisfied: portalocker==2.0.0 in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from sacrebleu>=1.4.12->fairseq==1.0.0a0+4c4d5a7) (2.0.0)
Requirement already satisfied: PyYAML>=5.1.* in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from omegaconf<2.1->fairseq==1.0.0a0+4c4d5a7) (5.3.1)
Requirement already satisfied: typing-extensions in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from omegaconf<2.1->fairseq==1.0.0a0+4c4d5a7) (3.7.4.2)
Requirement already satisfied: pycparser in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from cffi->fairseq==1.0.0a0+4c4d5a7) (2.20)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /home/cryptochat/anaconda3/lib/python3.8/site-packages (from importlib-resources; python_version < "3.9"->hydra-core<1.1->fairseq==1.0.0a0+4c4d5a7) (3.1.0)
Building wheels for collected packages: fairseq
  Building wheel for fairseq (PEP 517) ... done
  Created wheel for fairseq: filename=fairseq-1.0.0a0+4c4d5a7-cp38-cp38-linux_x86_64.whl size=2106379 sha256=e2eb7fe8efbf007312cb87eaf8f538cbdc88a00315aced82ac0532c7f4a5d722
  Stored in directory: /tmp/pip-ephem-wheel-cache-ysl4vpiz/wheels/d8/2a/fe/c8943070346a6761277e3915908a7c35cf666117b6859f058a
Successfully built fairseq
(base) machine@host:/usr/blah/genre$ ls
(base) machine@host:/usr/blah/genre$ python3
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fairseq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cryptochat/anaconda3/lib/python3.8/site-packages/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "/home/cryptochat/anaconda3/lib/python3.8/site-packages/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/home/cryptochat/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/cryptochat/anaconda3/lib/python3.8/site-packages/fairseq/criterions/label_smoothed_cross_entropy_latency_augmented.py", line 6, in <module>
    from examples.simultaneous_translation.utils.latency import LatencyTraining
ModuleNotFoundError: No module named 'examples'
>>> 
```

**Comment by DGaffney** [comment]
Re-read the instructions this morning and realized I was not supposed to install via a branch tag directly, but instead *clone the repository and install locally from that repo* - if the instructions could be cleared up a bit, that would be greatly appreciated for other people who may misinterpret the directions going forward:
```
git clone --branch fixing_prefix_allowed_tokens_fn https://github.com/nicola-decao/fairseq
cd fairseq
pip install --editable ./
```

**Comment by nicola-decao** [comment]
@DGaffney Thanks for pointing this out. I updated the documentation!
