### ISSUE TITLE
cant run the example code

### ISSUE THREAD

**Issue by qiuhaolu** [facebookresearch/GENRE#38]
Hello, thank you for sharing the code!

I met some issues when running the example inference code of GENRE. I followed the instructions on installing the dev version of fairseq. 

Any ideas why? Thanks.

Traceback (most recent call last):
  File "/disk/luqh/multilingualEL/fairseq/fairseq/data/data_utils.py", line 302, in batch_by_size
    from fairseq.data.data_utils_fast import (
  File "fairseq/data/data_utils_fast.pyx", line 1, in init fairseq.data.data_utils_fast
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    prefix_allowed_tokens_fn=lambda batch_id, sent: trie.get(sent.tolist()),
  File "/disk/luqh/multilingualEL/GENRE/genre/fairseq_model.py", line 43, in sample
    **kwargs,
  File "/disk/luqh/multilingualEL/GENRE/genre/fairseq_model.py", line 92, in generate
    return super(BARTHubInterface, self).generate(*args, **kwargs)
  File "/disk/luqh/multilingualEL/fairseq/fairseq/hub_utils.py", line 176, in generate
    for batch in self._build_batches(tokenized_sentences, skip_invalid_size_inputs):
  File "/disk/luqh/multilingualEL/fairseq/fairseq/hub_utils.py", line 269, in _build_batches
    disable_iterator_cache=True,
  File "/disk/luqh/multilingualEL/fairseq/fairseq/tasks/fairseq_task.py", line 289, in get_batch_iterator
    required_batch_size_multiple=required_batch_size_multiple,
  File "/disk/luqh/multilingualEL/fairseq/fairseq/data/fairseq_dataset.py", line 152, in batch_by_size
    fixed_shapes=fixed_shapes,
  File "/disk/luqh/multilingualEL/fairseq/fairseq/data/data_utils.py", line 314, in batch_by_size
    "Please build (or rebuild) Cython components with: `pip install "
ValueError: Please build (or rebuild) Cython components with: `pip install  --editable .` or `python setup.py build_ext --inplace`.

**Comment by qiuhaolu** [comment]
problem solved by install NumPy 1.2. It seems 1.18 is incompatible.
