### ISSUE TITLE
error in mgenre model.sample

### ISSUE THREAD

**Issue by ffaisal93** [facebookresearch/GENRE#55]
Hello,
I was trying to do entity linking on some sentences from different languages. I got this error:

code:
```
sentences= ['በምርጫው እንደማይወዳደሩ ቀደም ሲል ካስታወቁ በኋላ ፓርቲው በመጨረሻ ባካሄደው ጉባዔው [START] ዦዋዎ ሉሬንቾን [END] ቀዳሚው እጩ አድርጎ ሰይሟል ።']

 model.sample(
    sentences,
    prefix_allowed_tokens_fn=lambda batch_id, sent: [
        e for e in trie.get(sent.tolist()) if e < len(model.task.target_dictionary)
    ],
    text_to_id=lambda x: max(lang_title2wikidataID[tuple(reversed(x.split(" >> ")))], key=lambda y: int(y[1:])),
    marginalize=True,
)
```

error:
```
Traceback (most recent call last):
  File "temp.py", line 46, in <module>
    x = model.sample(
  File "/projects/antonis/fahim/ner_linking/GENRE/genre/fairseq_model.py", line 37, in sample
    batched_hypos = self.generate(
  File "/projects/antonis/fahim/ner_linking/GENRE/genre/fairseq_model.py", line 92, in generate
    return super(BARTHubInterface, self).generate(*args, **kwargs)
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/hub_utils.py", line 178, in generate
    translations = self.task.inference_step(
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/tasks/fairseq_task.py", line 501, in inference_step
    return generator.generate(
  File "/home/ffaisal/fairseq/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/sequence_generator.py", line 886, in generate
    finalized = super()._generate(sample, **kwargs)
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/sequence_generator.py", line 242, in _generate
    encoder_outs = self.model.forward_encoder(net_input)
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/sequence_generator.py", line 757, in forward_encoder
    return [model.encoder.forward_torchscript(net_input) for model in self.models]
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/sequence_generator.py", line 757, in <listcomp>
    return [model.encoder.forward_torchscript(net_input) for model in self.models]
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/models/fairseq_encoder.py", line 55, in forward_torchscript
    return self.forward_non_torchscript(net_input)
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/models/fairseq_encoder.py", line 62, in forward_non_torchscript
    return self.forward(**encoder_input)
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/models/transformer.py", line 437, in forward
    return self.forward_scriptable(src_tokens,
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/models/transformer.py", line 480, in forward_scriptable
    x, encoder_embedding = self.forward_embedding(src_tokens, token_embeddings)
  File "/projects/antonis/fahim/ner_linking/fairseq/fairseq/models/transformer.py", line 396, in forward_embedding
    token_embedding = self.embed_tokens(src_tokens)
  File "/home/ffaisal/fairseq/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ffaisal/fairseq/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/ffaisal/fairseq/lib/python3.8/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

kindly let me know if anyone has any idea how to solve this...this code works fine in some language sentence lists and in some cases like this, show this error. Thanks

**Comment by nicola-decao** [comment]
@ffaisal93 should be fixed now. Let me know.
